import { Barlow } from "next/font/google";
import "./globals.css";

export const barlow = Barlow({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
  style: ["normal"],
  display: "swap",
  variable: "--font-Barlow",
});

export const metadata = {
  title: "Thought Metrics",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${barlow.className}  antialiased`}>
      <body>{children}</body>
    </html>
  );
}
